### ISSUE TITLE
Deep parsing for instructions

### ISSUE THREAD

**Issue by Marsup** [mkdoc/mkpi#1]
Hi !

Do you think you would be open to a change to this library to allow for deep syntax substitution ?

What I mean by that is something like `# Title <? @macro return 'something' ?>` is not supported because it's not its own instruction.

I would find mkdoc even more useful if it were, I'm just wondering if it would not complicate it too much since it would then need escaping to not interpret your own documentation.

Curious what you think is best to support this (if at all).

**Comment by tmpfs** [comment]
Thanks for the input :)

I have no problem with inline processing instructions. You can see the difference in the AST with these commands:

```
echo '# title <? @macro return "foo" ?>' | mkcat | mkout -y
``` 

Which yields:

```yaml
---
- document:
  - heading:
    - text: 'title '
    - html_inline: '<? @macro return "foo" ?>'
---
```

And for blocks:

```
echo '# title\n\n<? @macro return "foo" ?>' | mkcat | mkout -y
```

Which gives a html block node:

```yaml
---
- document:
  - heading:
    - text: 'title'
  - html_block: '<? @macro return "foo" ?>'
---
```

I have submitted a PR to commonmark.js which would allow this, see:

https://github.com/jgm/commonmark.js/pull/97

My fork has this code already IIRC but I was hoping to get it into the upstream code before implementing, maybe you want to chime in on the PR so we might get it merged?
